# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z100ffv900-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /root/repo/new/ECE1373_GhostSynth/modules/latcherfloat/latcherfloat/solution1/impl/verilog/project.cache/wt [current_project]
set_property parent.project_path /root/repo/new/ECE1373_GhostSynth/modules/latcherfloat/latcherfloat/solution1/impl/verilog/project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /root/repo/new/ECE1373_GhostSynth/modules/latcherfloat/latcherfloat/solution1/impl/verilog/latcherfloatBlock_proc.v
  /root/repo/new/ECE1373_GhostSynth/modules/latcherfloat/latcherfloat/solution1/impl/verilog/latcherfloatlatcherfloat.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /root/repo/new/ECE1373_GhostSynth/modules/latcherfloat/latcherfloat/solution1/impl/verilog/latcherfloatlatcherfloat.xdc
set_property used_in_implementation false [get_files /root/repo/new/ECE1373_GhostSynth/modules/latcherfloat/latcherfloat/solution1/impl/verilog/latcherfloatlatcherfloat.xdc]


synth_design -top latcherfloatlatcherfloat -part xc7z100ffv900-1 -no_iobuf -mode out_of_context


write_checkpoint -force -noxdef latcherfloatlatcherfloat.dcp

catch { report_utilization -file latcherfloatlatcherfloat_utilization_synth.rpt -pb latcherfloatlatcherfloat_utilization_synth.pb }
