// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="latcherfloatlatcherfloat,hls_ip_2017_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z100ffv900-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.096000,HLS_SYN_LAT=0,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=37,HLS_SYN_LUT=63}" *)

module latcherfloatlatcherfloat (
        in_V_TDATA,
        out_V_TDATA,
        latch_V,
        ap_clk,
        ap_rst_n,
        in_V_TVALID,
        in_V_TREADY,
        out_V_TVALID,
        out_V_TREADY
);


input  [31:0] in_V_TDATA;
output  [31:0] out_V_TDATA;
input  [0:0] latch_V;
input   ap_clk;
input   ap_rst_n;
input   in_V_TVALID;
output   in_V_TREADY;
output   out_V_TVALID;
input   out_V_TREADY;

reg    ap_rst_n_inv;
wire    Block_proc_U0_ap_start;
wire    Block_proc_U0_ap_done;
wire    Block_proc_U0_ap_continue;
wire    Block_proc_U0_ap_idle;
wire    Block_proc_U0_ap_ready;
wire    Block_proc_U0_in_V_TREADY;
wire   [31:0] Block_proc_U0_out_V_TDATA;
wire    Block_proc_U0_out_V_TVALID;
wire    ap_sync_continue;
wire    Block_proc_U0_start_full_n;
wire    Block_proc_U0_start_write;

latcherfloatBlock_proc Block_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_proc_U0_ap_start),
    .ap_done(Block_proc_U0_ap_done),
    .ap_continue(Block_proc_U0_ap_continue),
    .ap_idle(Block_proc_U0_ap_idle),
    .ap_ready(Block_proc_U0_ap_ready),
    .latch_V(latch_V),
    .in_V_TDATA(in_V_TDATA),
    .in_V_TVALID(in_V_TVALID),
    .in_V_TREADY(Block_proc_U0_in_V_TREADY),
    .out_V_TDATA(Block_proc_U0_out_V_TDATA),
    .out_V_TVALID(Block_proc_U0_out_V_TVALID),
    .out_V_TREADY(out_V_TREADY)
);

assign Block_proc_U0_ap_continue = 1'b1;

assign Block_proc_U0_ap_start = 1'b1;

assign Block_proc_U0_start_full_n = 1'b0;

assign Block_proc_U0_start_write = 1'b0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b0;

assign in_V_TREADY = Block_proc_U0_in_V_TREADY;

assign out_V_TDATA = Block_proc_U0_out_V_TDATA;

assign out_V_TVALID = Block_proc_U0_out_V_TVALID;

endmodule //latcherfloatlatcherfloat
