// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _latcherfloatlatcherfloat_HH_
#define _latcherfloatlatcherfloat_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "latcherfloatBlock_proc.h"

namespace ap_rtl {

struct latcherfloatlatcherfloat : public sc_module {
    // Port declarations 9
    sc_in< sc_lv<32> > in_V_TDATA;
    sc_out< sc_lv<32> > out_V_TDATA;
    sc_in< sc_lv<1> > latch_V;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > in_V_TVALID;
    sc_out< sc_logic > in_V_TREADY;
    sc_out< sc_logic > out_V_TVALID;
    sc_in< sc_logic > out_V_TREADY;


    // Module declarations
    latcherfloatlatcherfloat(sc_module_name name);
    SC_HAS_PROCESS(latcherfloatlatcherfloat);

    ~latcherfloatlatcherfloat();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    latcherfloatBlock_proc* Block_proc_U0;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > Block_proc_U0_ap_start;
    sc_signal< sc_logic > Block_proc_U0_ap_done;
    sc_signal< sc_logic > Block_proc_U0_ap_continue;
    sc_signal< sc_logic > Block_proc_U0_ap_idle;
    sc_signal< sc_logic > Block_proc_U0_ap_ready;
    sc_signal< sc_logic > Block_proc_U0_in_V_TREADY;
    sc_signal< sc_lv<32> > Block_proc_U0_out_V_TDATA;
    sc_signal< sc_logic > Block_proc_U0_out_V_TVALID;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > Block_proc_U0_start_full_n;
    sc_signal< sc_logic > Block_proc_U0_start_write;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_Block_proc_U0_ap_continue();
    void thread_Block_proc_U0_ap_start();
    void thread_Block_proc_U0_start_full_n();
    void thread_Block_proc_U0_start_write();
    void thread_ap_rst_n_inv();
    void thread_ap_sync_continue();
    void thread_in_V_TREADY();
    void thread_out_V_TDATA();
    void thread_out_V_TVALID();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
